import Link from "next/link";
import Navigation from "@/components/landing/Navigation";
import Footer from "@/components/landing/Footer";
import { ShieldIcon } from "@/components/ui/icons";

export const metadata = {
  title: "Privacy Policy • ARKN",
  description:
    "ARKN Privacy Policy. Learn how MYARKN LTD collects, uses, and protects information when you use the ARKN browser extension and web dashboard.",
};

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-white font-sans text-gray-900 flex flex-col">
      <Navigation />

      <main className="flex-1 pt-32 pb-24 px-6 max-w-4xl mx-auto w-full">
        
        {/* Header */}
        <div className="border-b border-gray-100 pb-10 mb-12 space-y-4">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-50 border border-emerald-200/80 text-[12px] font-mono text-[#1A5C38] font-semibold">
            <ShieldIcon className="w-4 h-4 text-[#1A5C38]" />
            <span>Zero Raw Prompt Storage</span>
          </div>

          <h1 className="text-3xl sm:text-4xl md:text-5xl font-semibold text-gray-950 tracking-tight leading-tight">
            Privacy Policy
          </h1>

          <div className="flex items-center gap-4 text-xs text-gray-500 font-mono pt-2">
            <span>Last Updated: July 21, 2026</span>
            <span>•</span>
            <span>MYARKN LTD</span>
          </div>
        </div>

        {/* Policy Content */}
        <div className="space-y-10 text-[15px] leading-relaxed text-gray-700 font-normal">
          
          {/* Introduction */}
          <div className="bg-[#f4f5f6] rounded-2xl p-6 sm:p-8 space-y-4">
            <p className="text-gray-900 font-medium leading-relaxed">
              This Privacy Policy explains how MYARKN LTD (&quot;ARKN&quot;, &quot;we&quot;, &quot;our&quot;, or &quot;us&quot;) collects, uses, and protects information when you use the ARKN browser extension, web dashboard, and related services.
            </p>
            <p className="text-gray-600 text-sm leading-relaxed">
              ARKN is designed to protect sensitive information before it reaches AI services. The extension performs detection, tokenization, and restoration locally on your device. As a result, we do not receive, store, or process your original prompts or the sensitive information contained within them.
            </p>
          </div>

          {/* 1. Information We Do Not Collect */}
          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-gray-950 tracking-tight">1. Information We Do Not Collect</h2>
            <p>ARKN is architected so that sensitive information remains on your device.</p>
            <p>We do not collect, store, or transmit:</p>
            <ul className="list-disc pl-6 space-y-2 text-gray-600">
              <li>Original prompts submitted to ChatGPT, Claude, Gemini, or other supported AI services.</li>
              <li>Personally Identifiable Information (PII), including names, email addresses, phone numbers, postal addresses, identification numbers, or similar personal data contained within prompts.</li>
              <li>Customer records, contracts, legal documents, medical information, financial information, or confidential business documents processed by the extension.</li>
              <li>API keys, passwords, OAuth tokens, authentication credentials, or other secrets detected within prompts.</li>
              <li>Responses generated by third-party AI providers.</li>
              <li>Prompt content for analytics, profiling, or model training.</li>
            </ul>
            <p className="text-sm font-medium text-gray-900 pt-1">
              Your prompts are never used to train ARKN systems, third-party AI models, or any machine learning models.
            </p>
          </section>

          {/* 2. Information We Collect */}
          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-gray-950 tracking-tight">2. Information We Collect</h2>
            <p>
              To operate the ARKN platform, we collect only the information necessary to authenticate users, manage organizations, and provide workspace-level reporting.
            </p>

            <div className="space-y-4 pt-2">
              <div className="bg-white border border-gray-100 rounded-xl p-5 space-y-2">
                <h3 className="text-sm font-semibold text-gray-950">Account Information</h3>
                <ul className="list-disc pl-5 text-xs text-gray-600 space-y-1">
                  <li>Name</li>
                  <li>Work email address</li>
                  <li>Organization membership</li>
                  <li>Authentication identifiers</li>
                </ul>
              </div>

              <div className="bg-white border border-gray-100 rounded-xl p-5 space-y-2">
                <h3 className="text-sm font-semibold text-gray-950">Workspace Metadata</h3>
                <p className="text-xs text-gray-600">We collect anonymized operational metadata, including:</p>
                <ul className="list-disc pl-5 text-xs text-gray-600 space-y-1">
                  <li>Number of protected entities</li>
                  <li>Types of protected entities (for example: EMAIL, PHONE, API_KEY)</li>
                  <li>AI platform used (such as ChatGPT, Claude, or Gemini)</li>
                  <li>Protection latency</li>
                  <li>Extension version</li>
                  <li>Device status</li>
                  <li>Last active timestamp</li>
                </ul>
              </div>
            </div>

            <p className="text-sm text-gray-500 italic pt-1">
              This information does not include your original prompt or any protected values.
            </p>
          </section>

          {/* 3. How We Use Information */}
          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-gray-950 tracking-tight">3. How We Use Information</h2>
            <p>We use the information we collect to:</p>
            <ul className="list-disc pl-6 space-y-1.5 text-gray-600">
              <li>Authenticate users.</li>
              <li>Manage organizations and workspaces.</li>
              <li>Display protection statistics within the dashboard.</li>
              <li>Monitor extension health and connected devices.</li>
              <li>Improve product reliability and performance.</li>
              <li>Detect abuse or unauthorized access.</li>
            </ul>
            <div className="bg-emerald-50/60 border border-emerald-100 rounded-xl p-4 space-y-1 text-xs text-[#1A5C38] font-medium pt-2">
              <p>● We do not sell personal information.</p>
              <p>● We do not build advertising profiles.</p>
              <p>● We do not use customer prompts to train AI models.</p>
            </div>
          </section>

          {/* 4. Local Processing */}
          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-gray-950 tracking-tight">4. Local Processing</h2>
            <p>The ARKN browser extension performs sensitive data protection locally on your device.</p>
            <p>This includes:</p>
            <ul className="list-disc pl-6 space-y-1.5 text-gray-600">
              <li>Detection of sensitive information.</li>
              <li>Tokenization of protected values.</li>
              <li>Temporary token mapping required to restore values within your browser.</li>
              <li>Prompt reconstruction after AI responses are received.</li>
            </ul>
            <p className="text-sm text-gray-500">
              These operations occur within the browser runtime before information is transmitted to third-party AI services.
            </p>
          </section>

          {/* 5. Local Storage */}
          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-gray-950 tracking-tight">5. Local Storage</h2>
            <p>
              The extension may temporarily store token mappings and session state using browser storage mechanisms required for normal operation.
            </p>
            <p>This information:</p>
            <ul className="list-disc pl-6 space-y-1.5 text-gray-600">
              <li>remains on your device,</li>
              <li>is used only to restore protected values,</li>
              <li>is not transmitted to ARKN servers,</li>
              <li>is removed when no longer required for functionality.</li>
            </ul>
          </section>

          {/* 6. Security */}
          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-gray-950 tracking-tight">6. Security</h2>
            <p>
              We use industry-standard administrative, technical, and organizational safeguards to protect information processed by our platform.
            </p>
            <p>These measures include:</p>
            <ul className="list-disc pl-6 space-y-1.5 text-gray-600">
              <li>Encryption in transit using TLS.</li>
              <li>Encryption of stored account and workspace metadata.</li>
              <li>Role-based access controls.</li>
              <li>Workspace-level data isolation.</li>
              <li>Regular security updates and monitoring.</li>
            </ul>
            <p className="text-sm text-gray-500 italic">
              No security system can guarantee absolute protection; however, we continuously improve our security practices to reduce risk.
            </p>
          </section>

          {/* 7. Data Retention */}
          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-gray-950 tracking-tight">7. Data Retention</h2>
            <p>
              Account information and workspace metadata are retained only for as long as necessary to provide the service or comply with legal obligations.
            </p>
            <p className="font-medium text-gray-900">
              Original prompts and protected values are not retained by ARKN.
            </p>
          </section>

          {/* 8. Third-Party AI Providers */}
          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-gray-950 tracking-tight">8. Third-Party AI Providers</h2>
            <p>ARKN integrates with AI services including, but not limited to:</p>
            <ul className="list-disc pl-6 space-y-1 text-gray-600">
              <li>ChatGPT</li>
              <li>Claude</li>
              <li>Gemini</li>
            </ul>
            <p>
              ARKN protects supported sensitive information before requests are transmitted to these providers.
            </p>
            <p className="text-sm text-gray-500">
              Use of those services remains subject to their respective privacy policies and terms.
            </p>
          </section>

          {/* 9. Your Rights */}
          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-gray-950 tracking-tight">9. Your Rights</h2>
            <p>Depending on your jurisdiction, you may have the right to:</p>
            <ul className="list-disc pl-6 space-y-1.5 text-gray-600">
              <li>Access your personal information.</li>
              <li>Correct inaccurate information.</li>
              <li>Request deletion of your account.</li>
              <li>Request export of your personal information.</li>
              <li>Object to or restrict certain processing activities where applicable.</li>
            </ul>
            <p className="text-sm text-gray-500">
              Requests may be submitted using the contact information below.
            </p>
          </section>

          {/* 10. International Data Transfers */}
          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-gray-950 tracking-tight">10. International Data Transfers</h2>
            <p>
              Depending on where you are located, your account information and workspace metadata may be processed in countries outside your jurisdiction.
            </p>
            <p>
              Where required by law, we implement appropriate safeguards for international transfers.
            </p>
          </section>

          {/* 11. Children's Privacy */}
          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-gray-950 tracking-tight">11. Children's Privacy</h2>
            <p>ARKN is intended for business and enterprise use.</p>
            <p>
              The service is not directed toward children under the age of 16, and we do not knowingly collect personal information from children.
            </p>
          </section>

          {/* 12. Changes to This Policy */}
          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-gray-950 tracking-tight">12. Changes to This Policy</h2>
            <p>We may update this Privacy Policy from time to time.</p>
            <p>
              If we make material changes, we will update the &quot;Last Updated&quot; date and provide notice through our website or dashboard where appropriate.
            </p>
          </section>

          {/* 13. Contact Us */}
          <section className="space-y-4 border-t border-gray-100 pt-8">
            <h2 className="text-xl font-semibold text-gray-950 tracking-tight">13. Contact Us</h2>
            <p>
              If you have questions about this Privacy Policy or how ARKN handles information, please contact us.
            </p>
            <div className="bg-gray-50 border border-gray-100 rounded-xl p-5 space-y-1.5 font-mono text-xs text-gray-700">
              <p className="font-semibold text-gray-950 text-sm">MYARKN LTD</p>
              <p>Email: <a href="mailto:hello@myarkn.ai" className="text-[#1A5C38] underline font-medium">hello@myarkn.ai</a></p>
              <p>Website: <a href="https://myarkn.ai" className="text-[#1A5C38] underline font-medium">https://myarkn.ai</a></p>
            </div>
          </section>

        </div>
      </main>

      <Footer />
    </div>
  );
}
