import Link from "next/link";
import Navigation from "@/components/landing/Navigation";
import Footer from "@/components/landing/Footer";
import { ShieldIcon } from "@/components/ui/icons";

export const metadata = {
  title: "Privacy Policy • ARKN",
  description:
    "ARKN Privacy Policy. Learn how our browser-first security layer protects sensitive PII locally without storing raw prompts or collecting customer data.",
};

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-white font-sans text-gray-900 flex flex-col">
      <Navigation />

      <main className="flex-1 pt-32 pb-24 px-6 max-w-4xl mx-auto w-full">
        
        {/* Header */}
        <div className="border-b border-gray-100 pb-10 mb-12 space-y-4">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-50 border border-emerald-200/80 text-[12px] font-mono text-[#1A5C38] font-semibold">
            <ShieldIcon className="w-4 h-4 text-[#1A5C38]" />
            <span>Zero Raw Data Collection</span>
          </div>

          <h1 className="text-3xl sm:text-4xl md:text-5xl font-semibold text-gray-950 tracking-tight leading-tight">
            Privacy Policy
          </h1>

          <div className="flex items-center gap-4 text-xs text-gray-500 font-mono pt-2">
            <span>Last updated: July 21, 2026</span>
            <span>•</span>
            <span>MYARKN LTD</span>
          </div>
        </div>

        {/* Policy Content */}
        <div className="space-y-12 text-[15px] leading-relaxed text-gray-700 font-normal">
          
          {/* Executive Summary */}
          <div className="bg-[#f4f5f6] rounded-2xl p-6 sm:p-8 space-y-3">
            <h2 className="text-base font-semibold text-gray-950 tracking-tight">Executive Summary</h2>
            <p className="text-gray-600 leading-relaxed text-sm">
              ARKN ("MYARKN LTD", "we", "us", or "our") operates a privacy-first security layer for enterprise AI tools. Our core architectural guarantee is simple: <strong>Raw sensitive data, PII, credentials, and business prompts never leave your local device.</strong> All inspection, entity detection, tokenization, and text restoration occur 100% locally inside your browser sandbox.
            </p>
          </div>

          {/* Section 1 */}
          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-gray-950 tracking-tight">1. Information We Do NOT Collect</h2>
            <p>
              Unlike conventional SaaS platforms, ARKN is engineered to prevent raw data ingestion. We explicitly <strong>do not collect, store, or transmit</strong>:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-gray-600">
              <li>Raw conversation prompts typed into ChatGPT, Claude, Gemini, or any AI platform.</li>
              <li>Unmasked Personally Identifiable Information (PII) such as real names, email addresses, phone numbers, postcodes, or National Insurance numbers.</li>
              <li>Customer records, medical notes, clinical details, financial sort codes, or legal documents.</li>
              <li>API keys, passwords, OAuth tokens, or confidential corporate credentials.</li>
              <li>Model completion responses generated by third-party LLMs.</li>
            </ul>
            <p className="text-sm text-gray-500 italic pt-1">
              Your prompts are never used to train ARKN models, third-party AI systems, or anyone else's algorithms.
            </p>
          </section>

          {/* Section 2 */}
          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-gray-950 tracking-tight">2. Information We Process & Synchronize</h2>
            <p>
              To provide organization-wide security dashboards, compliance auditing, and active device monitoring, ARKN processes and synchronizes only <strong>anonymous, non-identifiable protection metadata</strong>:
            </p>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-2">
              <div className="bg-white border border-gray-100 rounded-xl p-5 space-y-2">
                <h3 className="text-sm font-semibold text-gray-950">Anonymous Protection Metrics</h3>
                <p className="text-xs text-gray-500 leading-relaxed">
                  Counts of redacted entities (e.g. 3 items protected), entity types (e.g. 1 x EMAIL, 1 x API_KEY), platform usage (ChatGPT, Claude, Gemini), and local execution latency.
                </p>
              </div>

              <div className="bg-white border border-gray-100 rounded-xl p-5 space-y-2">
                <h3 className="text-sm font-semibold text-gray-950">Device & Account Status</h3>
                <p className="text-xs text-gray-500 leading-relaxed">
                  Active device heartbeats (device name, OS version, extension release version, last online timestamp) and authenticated account details (work email, organization membership).
                </p>
              </div>
            </div>
          </section>

          {/* Section 3 */}
          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-gray-950 tracking-tight">3. Chrome Extension Manifest V3 Compliance</h2>
            <p>
              The ARKN Chrome Extension operates within Google Chrome's Manifest V3 security framework:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-gray-600">
              <li>
                <strong>Host Permissions:</strong> Host permissions requested in <code>manifest.json</code> (e.g., <code>chatgpt.com</code>, <code>claude.ai</code>, <code>gemini.google.com</code>) are used strictly to inject real-time local network interceptors and perform client-side PII replacement.
              </li>
              <li>
                <strong>Local Storage (<code>chrome.storage.local</code>):</strong> Temporary deterministic token mappings (e.g. <code>&#123;NAME_1&#125;</code> ➔ <code>Sarah Jenkins</code>) are held in ephemeral local storage inside your browser memory to restore values locally on screen. They are never sent to remote servers.
              </li>
              <li>
                <strong>No Single Sign-On Ingestion:</strong> Session tokens used for dashboard login are transferred over encrypted local postMessage bridges strictly for authentication validation.
              </li>
            </ul>
          </section>

          {/* Section 4 */}
          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-gray-950 tracking-tight">4. Data Security & Storage</h2>
            <p>
              Where account or metadata storage is required (such as organization member lists or compliance audit summaries):
            </p>
            <ul className="list-disc pl-6 space-y-2 text-gray-600">
              <li>All database queries are enforced using strict Row Level Security (RLS) data isolation.</li>
              <li>Data in transit is encrypted using standard TLS 1.3 / HTTPS.</li>
              <li>Data at rest is stored in SOC 2 Type II compliant cloud infrastructure.</li>
            </ul>
          </section>

          {/* Section 5 */}
          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-gray-950 tracking-tight">5. Regulatory Compliance</h2>
            <p>
              ARKN is designed to assist regulated enterprises in complying with global privacy frameworks:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-gray-600">
              <li><strong>UK & EU GDPR:</strong> Full compliance through local client-side processing, zero raw data retention, and data minimization principles.</li>
              <li><strong>HIPAA & Clinical PII:</strong> Local checksum validation and immediate entity masking for medical records.</li>
            </ul>
          </section>

          {/* Section 6 */}
          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-gray-950 tracking-tight">6. Changes to This Policy</h2>
            <p>
              We may update this Privacy Policy periodically to reflect enhancements to our extension architecture or legal requirements. Material changes will be communicated via your organization dashboard or updated on our website.
            </p>
          </section>

          {/* Section 7 */}
          <section className="space-y-4 border-t border-gray-100 pt-8">
            <h2 className="text-xl font-semibold text-gray-950 tracking-tight">7. Contact Us</h2>
            <p>
              If you have any questions regarding this Privacy Policy or ARKN's security architecture, please contact our Data Protection Officer:
            </p>
            <div className="bg-gray-50 border border-gray-100 rounded-xl p-5 space-y-1 font-mono text-xs text-gray-700">
              <p className="font-semibold text-gray-900">MYARKN LTD</p>
              <p>Email: <a href="mailto:privacy@myarkn.ai" className="text-[#1A5C38] underline">privacy@myarkn.ai</a></p>
              <p>Website: <a href="https://myarkn.ai" className="text-[#1A5C38] underline">https://myarkn.ai</a></p>
            </div>
          </section>

        </div>
      </main>

      <Footer />
    </div>
  );
}
